version: '3.3'

services:
  consul:
    image: consul
    ports:
      - "8500:8500"
      - "8300:8300"
    command: agent -server -bootstrap -client=0.0.0.0
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - dkron

  dkron:
    image: dkron/dkron
    ports:
      - "8080:8080"
      - "8946"
      - "6868"
    depends_on:
      - consul
    volumes: 
      - type: bind 
        source: ~/dkron-config/dkron.db
        target: /dkron.db
    command: agent --server --backend=consul --backend-machine=consul:8500 --join=dkron:8946 --node-name=server --tag role=server
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - dkron

  dkron-agent:
    image: dkron/dkron
    ports:
      - "8946"
      - "6868"
    depends_on:
      - consul
    command: agent --backend=consul --backend-machine=consul:8500 --join=dkron:8946 --tag role=agent
    deploy:
      replicas: 3
    networks:
      - dkron

  visual:
    image: dockersamples/visualizer
    ports:
      - "5000:8080"
    depends_on:
      - dkron
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - dkron

networks:
  dkron: