version: '3.3'

services:
  consul:
    image: consul
    ports:
      - "8500:8500"
      - "8300:8300"
    command: agent -server -bootstrap -client=0.0.0.0

  dkron:
    image: dkron/dkron
    ports:
      - "8080:8080"
      - "8946"
      - "6868"
    volumes: 
      - type: bind 
        source: ~/dkron-config/dkron.db
        target: /dkron.db
    depends_on:
      - consul
    command: agent --server --backend=consul --backend-machine=consul:8500 --join=dkron:8946 --node-name=server --tag role=server

  dkron-agent:
    image: dkron/dkron
    ports:
      - "8946"
      - "6868"
    volumes: 
      - type: bind 
        source: ~/dkron-config/dkron.db/
        target: /dkron.db
    depends_on:
      - consul
    command: agent --backend=consul --backend-machine=consul:8500 --join=dkron:8946 --tag role=agent