version: '3'

services:
  consul:
    image: consul
    ports:
      - "8500:8500"
      - "8300"
    networks:
      - dkron
    hostname: node1
    command: agent -server -bootstrap -client=0.0.0.0



  dkron:
    image: dkron/dkron
    ports:
      - "8080:8080"
      - "8946"
      - "6868"
    networks:
      - dkron
    depends_on:
      - consul
    command: agent --server --backend=consul --backend-machine=consul:8500 --join=dkron:8946

networks:
  dkron: