# Definisi storage yang diinginkan
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 

---
# Storage yang diimplementasi
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2