apiVersion: v1
kind: Service
metadata:
  name: consul

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: consul

  ports:
    - name: http
      port: 8500
      nodePort: 8500
    
    - name: http
      port: 8300

  type: NodePort