apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  selector:
    matchLabels:
      app: consul
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul