apiVersion: v1
kind: Service
metadata:
  name: consul

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: consul

  ports:
    - name: front-end
      port: 8500
      nodePort: 30500
    
    - name: bac-kend
      port: 8300

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: dkron

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: dkron

  ports:
    - name: http
      port: 8080
      nodePort: 30080
    
    - name: communicator
      port: 8946

    - name: rpc
      port: 6868

  type: NodePort