# Definisi storage yang diinginkan
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-pvc
spec:
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi 

---
# Storage yang diimplementasi
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/consul/data"
    type: DirectoryOrCreate